### ISSUE TITLE
mulle-sde - Please add support for CudaText

### ISSUE THREAD

**Issue by 3oheicrw** [MulleFoundation/foundation-developer#6]
https://github.com/Alexey-T/CudaText

It's very similar to SublimeText and SublimeText plugins could be ported to CudaText easily.

@mulle-nat It's you deleted my ticket on mulle-sde repo? It can't disappear for no reasons.

**Comment by mulle-nat** [comment]
Yeah, it was just a link with no text. It looked like spam. At least here I have an inkling on what you want. 

I mean, wouldn't it be easier for you to do it, since I don't use that editor and I have no experience with it. Checkout the mulle-sde [sublime text](https://github.com/mulle-sde/mulle-sde-developer/tree/release/src/mulle-sde/sublime-text) extension. There are some support files in the root, which are easy to modify. The real action is in `project/all`, where the template for the editor is. There is also a [Wiki](https://github.com/mulle-sde/mulle-sde/wiki/Anatomy-of-an-extension) article "Anatomy of an extension", which is hopefully still up-to-date.

In the current release version, all that's in the template are the files and directories that the editor is supposed to ignore. 
In the next version, there will be also support for build systems in the template:

``` js
{
   "folders":
   [
      {
         "path": ".",
         "file_exclude_patterns":
         [
            "*~",
            "*~.*",
            "*.old",
            "*.chk",
            ".DS_Store",
            "._.DS_Store",
            "*.sublime-workspace",
            "tmp.*"
         ],
         "folder_exclude_patterns":
         [
            ".git",
            ".mulle/var",
            ".unison*",
            "addiction",
            "build",
            "Build",
            "kitchen",
            "dependency",
            "stash",
            "var"
         ],
         "binary_patterns":
         [
            "*.o",
            "*.lib",
            "*.log",
            "*.a",
            "*.so",
            "*.exe",
            "*.zip",
            "*.tgz",
            "*.bz2",
            "*.xz",
            "*.gif",
            "*.png",
            "*.jpg",
            "*.tiff"
         ]
      }
   ],
   "build_systems":
   [
      {
         "name": "Craft",
         "cmd": [ "mulle-sde", "craft" ],
         "working_dir": "${project_path}",
         "file_regex": "^(..[^:]*)(?::|\\()([0-9]+)(?::|\\))(?:([0-9]+):)?\\s*(.*)",
         "env": { "NO_COLOR": "YES" }
      },
      {
         "name": "Craft Debug",
         "cmd": [ "mulle-sde", "craft", "--debug" ],
         "working_dir": "${project_path}",
         "file_regex": "^(..[^:]*)(?::|\\()([0-9]+)(?::|\\))(?:([0-9]+):)?\\s*(.*)",
         "env": { "NO_COLOR": "YES" }
      },
      {
         "name": "Craft Release",
         "cmd": [ "mulle-sde", "craft", "--release"],
         "working_dir": "${project_path}",
         "file_regex": "^(..[^:]*)(?::|\\()([0-9]+)(?::|\\))(?:([0-9]+):)?\\s*(.*)",
         "env": { "NO_COLOR": "YES" }
      },
      {
         "name": "Clean",
         "cmd": [ "mulle-sde", "clean" ],
         "working_dir": "${project_path}",
         "file_regex": "^(..[^:]*)(?::|\\()([0-9]+)(?::|\\))(?:([0-9]+):)?\\s*(.*)",
         "env": { "NO_COLOR": "YES" }
      },
      {
         "name": "Clean All",
         "cmd": [ "mulle-sde", "clean", "all" ],
         "working_dir": "${project_path}",
         "file_regex": "^(..[^:]*)(?::|\\()([0-9]+)(?::|\\))(?:([0-9]+):)?\\s*(.*)",
         "env": { "NO_COLOR": "YES" }
      },
      {
         "name": "Clean Tidy",
         "cmd": [ "mulle-sde", "clean", "tidy" ],
         "working_dir": "${project_path}",
         "file_regex": "^(..[^:]*)(?::|\\()([0-9]+)(?::|\\))(?:([0-9]+):)?\\s*(.*)",
         "env": { "NO_COLOR": "YES" }
      }
   ]
}
```

You can have your own vendor/extension scheme, if you want. Place your extension as `3oheicrw/cuda-text` into `/usr/local/share/mulle-sde/extensions` and it should be found.

**Comment by mulle-nat** [comment]
BTW. The windows platform isn't well supported yet by the MulleFoundation. There is a lot of OS specific code, that I still have to write to bring it up to par with `linux` and `macos`. Maybe in the next release...
